# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-09 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20180708_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='deploy',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='work',
            name='github',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
